spring:
  security:
    oauth2:
      client:
        registration:
          spring-oauth2-client-demo:
            client-id: spring-oauth2-client
            client-secret: 221b6560-3771-4bd6-a29a-f3477d380b73
            provider: "local-docker-keycloak"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/home"
            scope: spring-oauth2-client
        provider:
          local-docker-keycloak:
            authorization-uri: http://localhost:8081/auth/realms/spring-oauth2/protocol/openid-connect/auth
            token-uri: http://localhost:8081/auth/realms/spring-oauth2/protocol/openid-connect/token