version: "3.8"
services:
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "8081:8080"
    volumes:
      - "./keycloak:/keycloak-config"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /keycloak-config/keycloak-config.json