version: "3.8"
services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./schema:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: password
  webapplication:
    depends_on: [ database ]
    build: ./
    image: spring-security-simple
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://database:5432/spring