version: "3.8"
services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./schema:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: password