spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: spring
    password: spring
    initialization-mode: always
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml